version: '3.7'

services:
    application:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/home/my-project/project
        working_dir: "/home/my-project/project"
        networks:
            - default
        ports:
            - "8080:8080"
